export declare class Bugs {
    GetBugDetailsbyBugIDs(bug_ids: string): Promise<any>;
    GetBugsbyBaseProductID(base_pid: string, page_index?: number, status?: 'O' | 'F' | 'T', modified_date?: '1' | '2' | '3' | '4' | '5', severity?: '1' | '2' | '3' | '4' | '5' | '6', sort_by?: 'status' | 'modified_date ' | 'severity' | 'support_case_count' | 'modified_date_earliest '): Promise<any>;
    GetBugsbyBaseProductIDandSoftwareReleases(base_pid: string, software_releases: string, page_index?: number, status?: 'O' | 'F' | 'T', modified_date?: '1' | '2' | '3' | '4' | '5', severity?: '1' | '2' | '3' | '4' | '5' | '6', sort_by?: 'status' | 'modified_date ' | 'severity' | 'support_case_count' | 'modified_date_earliest '): Promise<any>;
    GetSearchforBugsbyKeyword(keyword: string, page_index?: number, status?: 'O' | 'F' | 'T', modified_date?: '1' | '2' | '3' | '4' | '5', severity?: '1' | '2' | '3' | '4' | '5' | '6', sort_by?: 'status' | 'modified_date ' | 'severity' | 'support_case_count' | 'modified_date_earliest '): Promise<any>;
    GetSearchBugsbyProductSeriesAndAffectedSoftware(product_series: string, affected_releases: string, page_index?: number, status?: 'O' | 'F' | 'T', modified_date?: '1' | '2' | '3' | '4' | '5', severity?: '1' | '2' | '3' | '4' | '5' | '6', sort_by?: 'status' | 'modified_date ' | 'severity' | 'support_case_count' | 'modified_date_earliest '): Promise<any>;
    GetSearchBugsbyProductSeriesAndFixedInSoftware(product_series: string, fixed_in_releases: string, page_index?: number, status?: 'O' | 'F' | 'T', modified_date?: '1' | '2' | '3' | '4' | '5', severity?: '1' | '2' | '3' | '4' | '5' | '6', sort_by?: 'status' | 'modified_date ' | 'severity' | 'support_case_count' | 'modified_date_earliest '): Promise<any>;
    GetSearchBugsbyProductNameAndAffectedSoftware(product_name: string, affected_releases: string, page_index?: number, status?: 'O' | 'F' | 'T', modified_date?: '1' | '2' | '3' | '4' | '5', severity?: '1' | '2' | '3' | '4' | '5' | '6', sort_by?: 'status' | 'modified_date ' | 'severity' | 'support_case_count' | 'modified_date_earliest '): Promise<any>;
    GetSearchBugsbyProductNameAndFixedInSoftware(product_name: string, fixed_in_releases: string, page_index?: number, status?: 'O' | 'F' | 'T', modified_date?: '1' | '2' | '3' | '4' | '5', severity?: '1' | '2' | '3' | '4' | '5' | '6', sort_by?: 'status' | 'modified_date ' | 'severity' | 'support_case_count' | 'modified_date_earliest '): Promise<any>;
}
